//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Project_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Bid { get; set; }
        public string Btitle { get; set; }
        public string BCategory { get; set; }
        public string BDesc { get; set; }
        public string BUrl { get; set; }
    }
}
